### ISSUE TITLE
Stale issue bot

### ISSUE THREAD

**Issue by scagood** [AtomLinter/linter-eslint-node#40]
It might be worth including a stale issues bot, we could use the [stale action](https://github.com/actions/stale)

something like `.github/workflows/stale.yml`:
```yml
name: 'Close stale issues'
on:
  schedule:
    - cron: '30 1 * * *'

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          stale-issue-message: 'This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 5 days.'
          close-issue-message: 'This issue was closed because it has been stalled for 30 days with no activity.'
          days-before-stale: 30
          days-before-close: 5
          days-before-pr-close: -1 # Never close a PR
```
